In [2]:
import pandas as pd
import geopandas as gpd

In [10]:
building_footprint = gpd.read_file('um-building-footprint-edited.geojson')
building_footprint.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1042 entries, 0 to 1041
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   building_name  960 non-null    object
 1   building_id    1017 non-null   object
 2   campus         1042 non-null   object
 3   sub_campus     1042 non-null   object
 4   is_resource    1042 non-null   bool
 5   org            2 non-null      object
 6   description    2 non-null      object
 7   address        2 non-null      object
 8   service        1042 non-null   object
 9   email          1 non-null      object
 10  url            2 non-null      object
 11  geometry       1042 non-null   geometry
dtypes: bool(1), geometry(1), object(10)
memory usage: 90.7+ KB

In [4]:
building_footprint.loc[building_footprint['building_name'] == "Weiser Hall", "org"] = "Michigan Institute for Data & AI in Society"
building_footprint.loc[building_footprint['building_name'] == "Weiser Hall", "description"] = "We are a university-wide organization that advances data science and artificial intelligence (AI) and enables their transformative use across a wide range of research domains for lasting scientific and societal impact. We support innovative research and collaboration and provide research resources, offer training for faculty and other researchers, host three postdoctoral training programs, and develop extensive research collaboration with academia, industry and government."
building_footprint.loc[building_footprint['building_name'] == "Weiser Hall", "address"] = "500 Church Street, Ann Arbor MI 48109-1042"
building_footprint['service'] = [[] for _ in range(len(building_footprint))]
building_footprint.at[building_footprint[building_footprint['building_name'] == "Weiser Hall"].index[0],
                      "service"] = ["Consulting & Support", "Funding & Project Development", "Research & Methods"]
building_footprint.loc[building_footprint['building_name'] == "Weiser Hall", "email"] = "midas-research@umich.edu"

building_footprint.loc[building_footprint['building_name'] == "Weiser Hall", "url"] = "https://midas.umich.edu/"



building_footprint.loc[building_footprint['building_name'] == "NCRC Bldg 520", "org"] = "e-HAIL: E-Health & Artificial Intelligence"
building_footprint.loc[building_footprint['building_name'] == "NCRC Bldg 520", "description"] = "e-HAIL is a joint Michigan Medicine and College of Engineering initiative that aims to make U-M a premier hub for research that innovates in health through AI. Our focus is on collaboration, grant development, and infrastructure to support a multi-disciplinary approach to innovations in healthcare and AI/ML methodologies.The initiative provides several opportunities for researchers to connect and learn from others operating at the intersection of AI and health.We provide concrete support for preparing grant applications, including finding collaborators, grant writing assistance, and hiring student support."
building_footprint.loc[building_footprint['building_name'] == "NCRC Bldg 520", "address"] = "2800 Plymouth Rd, Ann Arbor, MI 48109"
building_footprint.at[building_footprint[building_footprint['building_name'] == "NCRC Bldg 520"].index[0], 
    "service"] = ["Applied & Domain Focused Research", "Funding & Project Development"]
building_footprint.loc[building_footprint['building_name'] == "NCRC Bldg 520", "url"] = "https://e-hail.umich.edu/"

In [18]:
building_footprint[building_footprint['building_name'] == "NCRC Bldg 520"]

,building_name,building_id,campus,sub_campus,is_resource,geometry,org,description,address,service,email,url
496,NCRC Bldg 520,1005281,Ann Arbor,North Campus,True,"POLYGON ((-83.70253 42.30066, -83.70253 42.300...",e-HAIL: E-Health & Artificial Intelligence,e-HAIL is a joint Michigan Medicine and Colleg...,"2800 Plymouth Rd, Ann Arbor, MI 48109","[Applied & Domain Focused Research, Funding & ...",NaN,https://e-hail.umich.edu/

In [5]:
building_footprint.to_file("um-building-footprint-edited.geojson", driver="GeoJSON")

In [11]:
building_footprint.building_id == '1005280'

0        True
1       False
2       False
3       False
4       False
        ...
1037    False
1038    False
1039    False
1040    False
1041    False
Name: building_id, Length: 1042, dtype: bool

In [3]:
resources = pd.read_csv("resources.csv")

In [4]:
resources

,building_id,resource_name,description,category,address,building_room,email,url,phone,audience,...,mon_close,tue_open,tue_close,wed_open,wed_close,thu_open,thu_close,fri_open,fri_close,comments
0,NaN,Advanced Research Computing,NaN,Computing and Technical Resource; Consulting &...,Please confirm address,Please confirm address,"arc-support@umich.edu, arc-consulting@umich.edu",https://its.umich.edu/advanced-research-computing,NaN,"Please speciify your target audience (faculty,...",...,NaN,9:30 AM,11:00 AM,1:30 PM,3:00 PM,NaN,NaN,NaN,NaN,Hours are for consulting services
1,1000145.0,Data Science for Dynamic Intervention Decision...,NaN,Applied & Domain Focused Research; Consulting ...,"426 Thompson St, Ann Arbor, MI 48106-1248",Institute for Social Research,d3-center@umich.edu,https://d3c.isr.umich.edu/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unable to find hours for either d3 or for ISR
2,1000204.0,Statistical Analysis of Biomedical and Educati...,NaN,Applied & Domain Focused Research; Consulting ...,"1415 Washington Heights, Ann Arbor, MI 48109",SPH I,SABER-proposals@umich.edu,https://sph.umich.edu/saber/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unable to find hours
3,1005282.0,Clinical & Health Research Dissemination & Imp...,NaN,Funding & Project Development,"1600 Huron Parkway, Ann Arbor, MI 48109",North Campus Research Complex Building 550,michr-rdc@umich.edu,https://michr.umich.edu/dissemination-implemen...,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1005281.0,e-HAIL: E-Health & Artificial Intelligence,NaN,Applied & Domain Focused Research; Funding & P...,"2800 Plymouth Rd, Ann Arbor, MI 48109",Building 520,Various (https://e-hail.umich.edu/people-e-hai...,https://e-hail.umich.edu/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unable to find hours
5,1005276.0,AI & Digital Health Innovation,NaN,Applied & Domain Focused Research; Computing &...,"1600 Huron Pkwy, Ann Arbor, MI 48109",Building 100,AIDHI@umich.edu,Please confirm website,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Michigan Alzheimer's Disease Center,NaN,Applied & Domain Focused Research,"2101 Commonwealth Blvd, Ste D., Ann Arbor, MI ...",Please confirm address,UM-Ask-MADC@med.umich.edu,https://medresearch.umich.edu/labs-departments...,734-936-8803,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1005092.0,AI Lab,NaN,"AI Development, Research & Methods; Consulting...","2260 Hayward Street, Ann Arbor, MI 48109-2121...",Bob and Betty Beyster Building,ailabadmin@umich.edu,https://ai.engin.umich.edu/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1005574.0,Michigan Institute for Computational Discovery...,NaN,"AI Development, Research & Methods; Computing ...","3520 Green Ct. Suite 2300, Ann Arbor, MI 48105",Please confirm address,micde-contact@umich.edu,https://micde.umich.edu/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1000193.0,Arts Research: Incubation & Acceleration (ARIA),NaN,"Arts, Humanities & Creative Practice; Funding ...","1109 Geddes Ave, Ann Arbor, MI 48109",Alexander G. Ruthven Building Suite 1300,ARIA.grant@umich.edu,https://research.umich.edu/arts-research-incub...,734-764-1185,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1005276.0,Center for Global Health Equity,NaN,"Applied & Domain Focused Research; Ethics, Soc...","1600 Huron Parkway, Ann Arbor, MI 48109",Building 100,globalhealthequity@umich.edu,https://globalhealthequity.umich.edu/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1000166.0,Michigan Center for Applied and Interdisciplin...,NaN,"AI Research, Development & Methods; Consulting...","530 Church Street, Ann Arbor, MI 48109-1043",2074 East Hall,math-mcaim@umich.edu,https://sites.lsa.umich.edu/mcaim/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1000193.0,Bold Challenges,NaN,Funding & Project Development,"1109 Geddes Ave, Ann Arbor, MI 48109",Alexander G. Ruthven Building,Please confirm email,Please confirm website,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1000145.0,"Center for Ethics, Society, and Computing (ESC)",NaN,"Ethics, Society & Policy; Applied & Domain Foc...","426 Thompson Street, Ann Arbor, MI 48104-1248",Institute for Social Research,esc-center@umich.edu,https://esc.umich.edu/,(734) 764-5361,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1000197.0,Digital Studies Institute,NaN,"Ethics, Society & Policy; Arts, Humanities & C...","419 S. State St, Ann Arbor, MI 48109-1045",G333 Mason Hall,umdsi.info@umich.edu,https://www.digitalstudies.umich.edu/,734-764-3356,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1005101.0,"Science, Technology, and Public Policy (STPP) ...",NaN,"Ethics, Society & Policy; Applied & Domain Foc...","735 South State Street, Ann Arbor, MI 48109",Weill Hall/Gerald R. Ford School of Public Policy,stpp@umich.edu,https://stpp.fordschool.umich.edu/topic-areas/...,(734) 764-0453,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,AI Institutes at Michigan (AIIM),NaN,"AI Research, Development & Methods; Applied & ...",Please confirm address,Please confirm address,AIIM-Info@umich.edu,https://aiim.umich.edu/request-for-submissions/,NaN,"Please speciify your target audience (faculty,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1000165.0,Michigan Institute for Data & AI in Society,NaN,NaN,"500 Church Street, Ann Arbor MI 48109-1042",Weiser Hall,midas-research@umich.edu,https://midas.umich.edu/,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN